version: '3.7'

services:
  db:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    environment:
      - MYSQL_USER=hello_django # change to whatever username you want
      - MYSQL_PASSWORD=hello_django #change to the password you want for user
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=hello_django_dev # name you want for the database
    ports:
      - 3306:3306
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
#  db:
#    image: postgres:12.0-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_USER=hello_django
#      - POSTGRES_PASSWORD=hello_django
#      - POSTGRES_DB=hello_django_dev

volumes:
  mysql_data:
